PPUCTRL =   $2000
PPUMASK =   $2001
PPUSTATUS = $2002
PPUADDR =   $2006
PPUDATA =   $2007
OAMADDR =   $2003
OAMDMA  =   $4014
PPUSCROLL = $2005
DMCIRQ    = $4010
APUSOUND  = $4015
JOY_PAD1  = $4016
JOY_PAD2  = $4017


; Битовые маски кнопок стандартных геймпадов
KEY_RIGHT               = %00000001
KEY_LEFT                = %00000010
KEY_DOWN                = %00000100
KEY_UP                  = %00001000
KEY_START               = %00010000
KEY_SELECT              = %00100000
KEY_B                   = %01000000
KEY_A                   = %10000000

